# Author: Aneeq H. Khan
# Build CI For the Demo Site Hosted on Azure

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Running Unit Tests'
  inputs:
    command: test
    projects: '**/*UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Building Project'

- task: DotNetCoreCLI@2
  displayName: 'Publishing Project'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'AzureDemo/AzureDemo.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: 'Publishing Integration Tests'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'DemoWebsite.IntegrationTests/AzureDemo.IntegrationTests.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Artifacts'